server:
  port: 8080


spring:
  profiles:
    active: @profiles.active@
  #    需要增加文件路径匹配，不然回报错，导致项目起不来
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  config: classpath:logback-spring.xml
  level:
    root: INfO
