sto:
  url: https://cloudinter-linkgateway.sto.cn/gateway/link.do
zto:
  url: https://japi-test.zto.com/zto.msg.sms.checkBillCode
jt:
  url: https://openapi.jtexpress.com.cn/webopenplatformapi/api/sms/getMobile
